### ISSUE TITLE
mod返回的语音数据无法获取？

### ISSUE THREAD

**Issue by BadDeveloper2022** [lionsoul2014/freeswitch-asr#3]
我把里面的接口改成自己的http接口了，
然后mod上传来的语音数据保存到本地分析了
全是 嘟嘟 声音，而且全是1秒的
没改东西，只改了接口
配置文件是参考你项目里面的 ，也没改参数

**Comment by BadDeveloper2022** [comment]
PCM数据格式是什么样的？
16bit 还是8bit

**Comment by Sabirjan** [comment]
分析了半天才知道。。。。这个16位 的PCM 
好像被压缩的
我把采样率设置3100 才能正常听
16000 都不行

**Comment by BadDeveloper2022** [comment]
PCM数据无法转换，能不能指导一下，非常感谢。

**Comment by BadDeveloper2022** [comment]
我想转换成wav，但是好像参数不准确，转换出来的数据不是正常的

**Comment by BadDeveloper2022** [comment]
` /* resample the data */
        resamples = samples / 3;
        for ( c = 0; c < samples; c += 3 ) {
            one_sample = (data[c] + data[c+1] + data[c+2]) / 3;
            switch_buffer_write(yyasr->audio_buffer, &one_sample, sizeof(int16_t));
        }

        yyasr->audio_size += resamples * sizeof(int16_t);
        if ( yyasr->audio_size >= globals.audio_buffer_max_size ) {
            yyasr->audio_size = globals.audio_buffer_max_size;
            switch_set_flag_locked(yyasr, YY_FLAG_SPEECH_TIMEOUT);
            return SWITCH_TRUE;
        }`

@lionsoul2014 这个什么意思？

**Comment by BadDeveloper2022** [comment]
解决了
`int datalen = resamples * sizeof(int16_t);
		yyasr->audio_size += datalen;
		switch_buffer_write(yyasr->audio_buffer, data, datalen);`
